import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import NavBar from "@/components/NavBar";
import BreadCrumb from "@/components/Breadcrumb/BreadCrumb";
import Footer from "@/components/Footer";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Nhannik",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased text-black",fontSans.variable)}>
        <NavBar/>
        <BreadCrumb/>
        <Theme>
          {children}
        </Theme>
        <Footer />
      </body>
    </html>
  );
}
